/*
 * M_DIO_config.h
 *
 *  Created on: Aug 31, 2019
 *      Author: osama
 */

#ifndef M_DIO_CONFIG_H_
#define M_DIO_CONFIG_H_

#define PIN0_MODE			M_DIO_OUTPUT
#define PIN1_MODE			M_DIO_OUTPUT
#define PIN2_MODE			M_DIO_OUTPUT
#define PIN3_MODE			M_DIO_OUTPUT
#define PIN4_MODE			M_DIO_OUTPUT
#define PIN5_MODE			M_DIO_OUTPUT
#define PIN6_MODE			M_DIO_OUTPUT
#define PIN7_MODE			M_DIO_OUTPUT
#define PIN8_MODE			M_DIO_INPUT_PULLUP
#define PIN9_MODE			M_DIO_INPUT_PULLUP
#define PIN10_MODE			M_DIO_INPUT_PULLUP
#define PIN11_MODE			M_DIO_INPUT_PULLUP
#define PIN12_MODE			M_DIO_INPUT_PULLUP
#define PIN13_MODE			M_DIO_INPUT_PULLUP
#define PIN14_MODE			M_DIO_INPUT_PULLUP
#define PIN15_MODE			M_DIO_INPUT_PULLUP
#define PIN16_MODE			M_DIO_OUTPUT
#define PIN17_MODE			M_DIO_OUTPUT
#define PIN18_MODE			M_DIO_OUTPUT
#define PIN19_MODE			M_DIO_OUTPUT
#define PIN20_MODE			M_DIO_OUTPUT
#define PIN21_MODE			M_DIO_OUTPUT
#define PIN22_MODE			M_DIO_OUTPUT
#define PIN23_MODE			M_DIO_OUTPUT
#define PIN24_MODE			M_DIO_INPUT_PULLUP
#define PIN25_MODE			M_DIO_INPUT_PULLUP
#define PIN26_MODE			M_DIO_INPUT_PULLUP
#define PIN27_MODE			M_DIO_INPUT_PULLUP
#define PIN28_MODE			M_DIO_INPUT_PULLUP
#define PIN29_MODE			M_DIO_INPUT_PULLUP
#define PIN30_MODE			M_DIO_INPUT_PULLUP
#define PIN31_MODE			M_DIO_INPUT_PULLUP

#endif /* INCLUDE_M_DIO_CONFIG_H_ */
